### ISSUE TITLE
Get CAM Software

### ISSUE THREAD

**Issue by AForland** [RRCCDataLab/RRCC_Laser_Lab#9]

**Comment by endlesstankzone** [comment]
After doing some research i believe i found a good opensource option for the laser cutter cam software. After downloading a few free open source software suites, the best one i was able to find was a plugin for Inkscape. Inkscape is a open source vector graphics editor that open source and free to use. Because its opensource many people have created plugins for various things. A company by the name of J tech Photonics has created a plugin for Inkscape that lets you cut/engrave images or DXF/DWG files easily through there plugin. I tested a couple of things like text, images, and shapes and it appears to be turning the laser on and off correctly and moving the machine around in a predictable way. 

Inkscape: https://inkscape.org/en/

Laser Plugin: https://jtechphotonics.com/?page_id=2012
